namespace: qlik
name: cloud
version: 0.1.0
readme: README.md
authors:
  - Adam Haydon (https://github.com/ahaydon)
description: Qlik Cloud modules and plugins for Ansible
license:
  - MIT
tags:
  - qlik
  - sense
  - cloud
  - saas
repository: https://github.com/QlikProfessionalServices/ansible-qlikcloud-collection
documentation: ''
homepage: https://github.com/QlikProfessionalServices/ansible-qlikcloud-collection
issues: https://github.com/QlikProfessionalServices/ansible-qlikcloud-collection/issues
build_ignore:
  - dest
  - docs
  - .vscode
  - tests
  - .gitignore
